Integrate minimap with LASTeam based icons
Terasology/LightAndShadow pull request #104
Opened 2019-08-15 23:09 UTC by darshan3

2019-08-18 16:02 UTC, iaronaraujo approved these changes

2019-08-20 18:44 UTC, skaldarnar requested changes

2019-08-20 18:44 UTC, skaldarnar commented on src/main/java/org/terasology/ligthandshadow/componentsystem/LASUtils.java
> +    public static final String RED_MINIMAP_ICON = "lightAndShadowResources:heartsIcon";
As pointed out in https://github.com/Terasology/LightAndShadowResources/pull/31#pullrequestreview-277364660 you might just use the icons that are already there:
```suggestion
    public static final String RED_MINIMAP_ICON = "lightAndShadowResources:heart";
```

2019-08-20 18:44 UTC, skaldarnar commented on src/main/java/org/terasology/ligthandshadow/componentsystem/LASUtils.java
> +    public static final String BLACK_MINIMAP_ICON = "lightAndShadowResources:spadesIcon";
As pointed out in https://github.com/Terasology/LightAndShadowResources/pull/31#pullrequestreview-277364660 you might just use the icons that are already there:
```suggestion
    public static final String BLACK_MINIMAP_ICON = "lightAndShadowResources:spade";
```

2020-05-22 18:10 UTC, jdrueckert approved these changes

2020-05-22 18:11 UTC, merged