feat: add a UIImage next to the answer UIButton
Terasology/LightAndShadow pull request #139
Opened 2020-07-29 17:04 UTC by stefaniamak

### Tasks
- [ ] set UIImage next to the UIButton - WIP
- [ ] set UIImage to show the new arrow asset if the button next to it is hovered with the mouse - WIP https://github.com/Terasology/LightAndShadowResources/pull/53

### Purpose

Set an arrow asset to appear in the appropriate UIImage next to the hoved UIButton.

2020-07-29 19:03 UTC, skaldarnar requested changes
As described in https://github.com/Terasology/Dialogs/pull/15#pullrequestreview-457797353 the actual image to display should be configured via the `MagicFool.prefab`.

2020-08-03 13:00 UTC, stefaniamak commented
> 
> 
> As described in [Terasology/Dialogs#15 (review)](https://github.com/Terasology/Dialogs/pull/15#pullrequestreview-457797353) the actual image to display should be configured via the `MagicFool.prefab`.

Yes! Not 100% sure if we need the extra column or not in the end, but if we end up not needing it then this PR can close.

2020-08-04 18:09 UTC, skaldarnar commented on assets/prefabs/MagicFool.prefab
> +                        "responseImage": "LightAndShadowResources:heartsIcon",
👍

2020-08-17 03:27 UTC, Cervator reviewed
Have tested this out along with the two other related PRs - seems fine! 👍 

Clearly a fair bit of back-and-forth review cycles have happened with a bunch of commits with relatively few changes, so I'm going to opt for squash merging these. Changes seem relatively straight forward and nothing really jumps out at me :-)

Nicely done!

2020-08-17 03:28 UTC, merged